language: java

services:
 - elasticsearch
  
before_script:
 - sleep 10
  
before_install:
 - curl -O https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-6.1.1.deb && sudo dpkg -i --force-confnew elasticsearch-6.1.1.deb && sudo service elasticsearch restart

script: 
 - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
 - mvn test
