language: java

jdk:
 - oraclejdk8
 
addons:
  hosts:
   - elasticsearch

install:
 - mvn -N io.takari:maven:wrapper

script:
 - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
 - mvn test || mvn test

branches:
  only:
    - master
